### PR TITLE
CONTENT ADD: Add front-end challenge

### PR DESCRIPTION
**Pull request by vincentiusantu**
I just added challenge about front-end. The academicians have to create personal website that has some requirements stated in the markdown.

### CODE REVIEW

**Review by Soedipo — APPROVED** [review]
As for me, I approve it because we've discussed it together

**Review by adhiiimf — APPROVED** [review]

**Comment by vincentiusantu** [comment]
I just added Challenge 3: DOM Manipulation, the academician should make To-do List with some DOM manipulation.

**Review by adhiiimf — APPROVED** [review]
Done ya @vincentiusantu , nice cen! Goodluck for the academian

**Comment by vincentiusantu** [comment]
> Done ya @vincentiusantu , nice cen! Goodluck for the academian

Thanks for the review bang

**Pull request merged**
